name: Upload Python Package

on:
  push:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd sw/python
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        cd sw/python
        python3 setup.py egg_info -b ".dev`date '+%Y%m%d%H%M'`" build sdist
    - name: Deploy Pypi
      uses: remorses/pypi@v3
      with:
        setup_file: sw/python/setup.py
        username: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
